/**
 * One-click setup for OpenCode plugin.
 * Installs/removes a JS plugin at ~/.config/opencode/plugins/event-horizon.ts
 * that forwards OpenCode events to Event Horizon's HTTP server.
 *
 * OpenCode auto-loads .ts files from ~/.config/opencode/plugins/ at startup.
 * Users must restart OpenCode after installing the plugin.
 */

import * as vscode from 'vscode';
import * as fsp from 'fs/promises';
import * as path from 'path';
import * as os from 'os';
import { getAuthToken, getEventServerPort } from './eventServer.js';

function getPort(): number {
  return getEventServerPort();
}
const PLUGIN_FILENAME = 'event-horizon.ts';

/** Marker comment so we can identify our plugin file. */
const MARKER = '// @event-horizon/opencode-plugin';

function getPluginDir(): string {
  return path.join(os.homedir(), '.config', 'opencode', 'plugins');
}

function getPluginPath(): string {
  return path.join(getPluginDir(), PLUGIN_FILENAME);
}

function buildPluginSource(): string {
  const token = getAuthToken() ?? '';
  return `${MARKER}
// Auto-generated by Event Horizon VS Code extension.
// Forwards OpenCode events to the Event Horizon visualization server.
// Do not edit — reinstall from Event Horizon's Connect panel.

const PORT = ${getPort()};
const AUTH_TOKEN = "${token}";
const AUTH_HEADERS = AUTH_TOKEN
  ? { "Content-Type": "application/json", "Authorization": "Bearer " + AUTH_TOKEN }
  : { "Content-Type": "application/json" };

function send(eventName, extra) {
  const body = JSON.stringify({ event: eventName, ...extra });
  fetch("http://127.0.0.1:" + PORT + "/opencode", {
    method: "POST",
    headers: AUTH_HEADERS,
    body,
  }).catch(() => {});
}

async function checkLock(filePath, agentId, agentName) {
  try {
    const resp = await fetch("http://127.0.0.1:" + PORT + "/lock", {
      method: "POST",
      headers: AUTH_HEADERS,
      body: JSON.stringify({ action: "check", filePath, agentId, agentName }),
      signal: AbortSignal.timeout(2000),
    });
    if (resp.status === 409) {
      const data = await resp.json();
      throw new Error("[Event Horizon file lock] BLOCKED: " + filePath + " is locked by " + (data.owner || "another agent") + " who is actively editing it. You MUST NOT write to this file by ANY means — no Write, no Edit, no Bash echo/cat/sed, no workarounds. The lock will release automatically when they finish (within 30 seconds of their last write). Work on OTHER files first, then retry this file later.");
    }
  } catch (e) {
    if (e && e.message && e.message.includes("is locked by")) throw e;
    // Ignore network errors — Event Horizon might not be running
  }
}

async function releaseLock(filePath, agentId) {
  try {
    await fetch("http://127.0.0.1:" + PORT + "/lock", {
      method: "POST",
      headers: AUTH_HEADERS,
      body: JSON.stringify({ action: "release", filePath, agentId }),
      signal: AbortSignal.timeout(2000),
    });
  } catch {}
}

function sendExit(eventName, extra) {
  send(eventName, extra);
  try {
    const { spawnSync } = require("node:child_process");
    const body = JSON.stringify({ event: eventName, ...extra });
    const headerList = AUTH_TOKEN
      ? "'Content-Type':'application/json','Authorization':'Bearer " + AUTH_TOKEN + "'"
      : "'Content-Type':'application/json'";
    spawnSync("node", ["-e",
      "require('http').request({hostname:'127.0.0.1',port:" + PORT +
      ",path:'/opencode',method:'POST',headers:{" + headerList + "}}" +
      ",()=>process.exit()).end(" + JSON.stringify(body) + ")"
    ], { timeout: 2000, stdio: "ignore" });
  } catch {}
}

export default async function EventHorizon({ project, directory, worktree, serverUrl }) {
  // Use project.id when available, but always append a unique suffix so
  // multiple OpenCode instances in the same project get separate planets.
  const base = project?.id ? String(project.id) : "opencode";
  const uid = Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
  const sessionId = base + "-" + uid;

  // Resolve cwd — worktree/directory may be strings, URL objects, or absent.
  // Try every possible source, including process.cwd() as ultimate fallback.
  function resolvePath(v) {
    if (!v) return undefined;
    if (typeof v === "string") return v;
    if (typeof v === "object" && v.href) {
      // file:///C:/path or file:///home/path
      try { return new URL(v.href).pathname.replace(/^\\/([A-Z]:)/, "$1"); } catch {}
      return v.href.replace(/^file:\\/\\/\\//, "").replace(/^file:\\/\\//, "");
    }
    if (typeof v === "object" && v.pathname) return v.pathname;
    return String(v);
  }
  const cwd = resolvePath(worktree)
    || resolvePath(directory)
    || resolvePath(project?.path)
    || resolvePath(project?.directory)
    || resolvePath(project?.worktree)
    || (typeof process !== "undefined" && process.cwd ? process.cwd() : undefined);
  const cwdFolder = cwd ? String(cwd).replace(/\\\\/g, "/").split("/").pop() : undefined;
  const agentName = cwdFolder ? "OpenCode (" + cwdFolder + ")" : "OpenCode";
  // OpenCode's internal server URL — used by Event Horizon for SSE subagent tracking
  const opencodeServerUrl = typeof serverUrl === "object" && serverUrl?.href ? serverUrl.href : (typeof serverUrl === "string" ? serverUrl : undefined);

  // Send initial session.created
  send("session.created", { sessionId, agentName, cwd, payload: {}, serverUrl: opencodeServerUrl });

  // Continuously re-send session.created as a heartbeat so Event Horizon
  // can discover this agent even if it started after OpenCode.
  // Runs every 30 seconds indefinitely - Event Horizon deduplicates spawns.
  const heartbeatInterval = setInterval(() => {
    send("session.created", { sessionId, agentName, cwd, payload: { heartbeat: true }, serverUrl: opencodeServerUrl });
  }, 30000);

  // Send session.deleted when OpenCode exits (Ctrl+C, exit command, etc.)
  const onExit = () => {
    clearInterval(heartbeatInterval);
    sendExit("session.deleted", { sessionId, agentName, cwd, payload: {} });
  };
  process.on("beforeExit", onExit);
  process.on("SIGINT", () => { onExit(); process.exit(0); });
  process.on("SIGTERM", () => { onExit(); process.exit(0); });

  return {
    event: async ({ event }) => {
      send(event?.type ?? "unknown", {
        sessionId,
        agentName,
        cwd,
        payload: event ?? {},
      });
    },
    "tool.execute.before": async (input) => {
      const toolName = String(input?.tool || "");
      const fp = input?.input?.file_path || input?.input?.path;
      const parentID = input?.sessionID !== input?.parentID ? input?.parentID : undefined;
      send("tool.execute.before", {
        sessionId,
        agentName,
        cwd,
        payload: {
          toolName,
          sessionID: input?.sessionID,
          callID: input?.callID,
          filePath: fp ? String(fp) : undefined,
          parentID,
        },
      });
      // Check file lock for any tool that accesses files
      const toolLower = toolName.toLowerCase();
      const fileTool = ["read", "write", "edit", "patch", "file_read", "file_write", "file_edit"].includes(toolLower);
      if (fileTool && fp) {
        await checkLock(String(fp), sessionId, agentName);
      }
    },
    "tool.execute.after": async (input) => {
      const fp = input?.input?.file_path || input?.input?.path;
      send("tool.execute.after", {
        sessionId,
        agentName,
        cwd,
        payload: {
          toolName: input?.tool,
          sessionID: input?.sessionID,
          callID: input?.callID,
          filePath: fp ? String(fp) : undefined,
        },
      });
      // Locks NOT released here — auto-expire via 30s TTL.
      // Each tool.execute.before refreshes the TTL.
      if (false) { // keep releaseLock available for future use
        const fp = input?.input?.file_path || input?.input?.path;
        if (fp) await releaseLock(String(fp), sessionId);
      }
    },
    "permission.asked": async (input) => {
      send("permission.asked", {
        sessionId,
        agentName,
        cwd,
        payload: { tool: input?.tool, permission: input?.permission },
      });
    },
    "permission.replied": async (input) => {
      send("permission.replied", {
        sessionId,
        agentName,
        cwd,
        payload: { tool: input?.tool, granted: input?.granted },
      });
    },
  };
};
`;
}

/** Returns true if the Event Horizon plugin file exists (any token version). */
export async function isOpenCodeHooksInstalled(): Promise<boolean> {
  try {
    const content = await fsp.readFile(getPluginPath(), 'utf8');
    return content.includes(MARKER);
  } catch {
    return false;
  }
}

/** Returns true if the plugin file exists but with a stale token or legacy auth format. */
export async function hasStaleOpenCodeHooks(): Promise<boolean> {
  try {
    const content = await fsp.readFile(getPluginPath(), 'utf8');
    if (!content.includes(MARKER)) return false;
    // v2.0.0 breaking change: legacy ?token= URLs in the plugin are stale.
    if (content.includes('TOKEN_PARAM') || content.includes('?token=')) return true;
    const token = getAuthToken();
    if (token) return !content.includes(`AUTH_TOKEN = "${token}"`);
    return false;
  } catch {
    return false;
  }
}

/** Removes the Event Horizon plugin file. */
export async function removeOpenCodeHooks(): Promise<void> {
  const pluginPath = getPluginPath();
  try {
    const content = await fsp.readFile(pluginPath, 'utf8');
    if (content.includes(MARKER)) {
      await fsp.unlink(pluginPath);
    }
  } catch {
    // Nothing to remove
  }
}

/** Writes the Event Horizon plugin file. */
export async function setupOpenCodeHooks(): Promise<void> {
  const dir = getPluginDir();
  await fsp.mkdir(dir, { recursive: true });
  // Remove old .mjs version if present
  const oldMjs = path.join(dir, 'event-horizon.mjs');
  try { await fsp.unlink(oldMjs); } catch { /* ignore */ }
  await fsp.writeFile(getPluginPath(), buildPluginSource(), 'utf8');
  // Also update .opencode/config.json hooks if they exist (add auth token)
  await updateOpenCodeConfigHooks();
}

/** Update ~/.opencode/config.json hook URLs with the current auth token (Bearer header). */
async function updateOpenCodeConfigHooks(): Promise<void> {
  const configPath = path.join(os.homedir(), '.opencode', 'config.json');
  const token = getAuthToken();
  const port = getPort();
  const baseUrl = `http://127.0.0.1:${port}/opencode`;
  const authHeader = token ? `-H "Authorization: Bearer ${token}"` : '';
  try {
    const raw = await fsp.readFile(configPath, 'utf8');
    const config = JSON.parse(raw) as Record<string, unknown>;
    const hooks = config.hooks as Record<string, Array<Record<string, unknown>>> | undefined;
    if (!hooks) return;
    let changed = false;
    for (const entries of Object.values(hooks)) {
      for (const entry of entries) {
        if (typeof entry.command === 'string' && /127\.0\.0\.1:\d+\/opencode/.test(entry.command)) {
          const newCmd = `curl -s -X POST ${baseUrl} -H "Content-Type: application/json" ${authHeader} --data-binary @-`;
          if (entry.command !== newCmd) {
            entry.command = newCmd;
            changed = true;
          }
        }
      }
    }
    if (changed) {
      await fsp.writeFile(configPath, JSON.stringify(config, null, 2), 'utf8');
    }
  } catch { /* file doesn't exist or not writable — skip */ }
}

/**
 * Build an OpenCode MCP server entry (pure function, testable without FS).
 * Includes the startup token as a static Authorization header so first-party
 * clients connect directly; the hybrid `/mcp` route also accepts JWTs.
 */
export function buildOpenCodeMcpEntry(port: number, token: string | null): Record<string, unknown> {
  const entry: Record<string, unknown> = { type: 'remote', url: `http://127.0.0.1:${port}/mcp`, enabled: true };
  if (token) entry.headers = { Authorization: `Bearer ${token}` };
  return entry;
}

/**
 * Register Event Horizon as an MCP server in OpenCode's config.
 * Reads ~/.config/opencode/opencode.json, merges our entry under "mcp".
 */
export async function registerOpenCodeMcpServer(): Promise<void> {
  const configPath = path.join(os.homedir(), '.config', 'opencode', 'opencode.json');
  // v2.0.0+: hybrid auth — first-party clients send the startup token as a
  // Bearer header; third-party clients can still use OAuth 2.1 discovery.
  const token = getAuthToken();

  let config: Record<string, unknown> = {};
  try {
    const raw = await fsp.readFile(configPath, 'utf8');
    config = JSON.parse(raw);
  } catch {
    // File doesn't exist or is invalid — start fresh
  }

  const mcp = (config.mcp ?? {}) as Record<string, unknown>;
  mcp['event-horizon'] = buildOpenCodeMcpEntry(getPort(), token);
  config.mcp = mcp;

  const dir = path.dirname(configPath);
  await fsp.mkdir(dir, { recursive: true });
  await fsp.writeFile(configPath, JSON.stringify(config, null, 2), 'utf8');
}

export async function runSetupOpenCodeHooks(): Promise<void> {
  try {
    await setupOpenCodeHooks();
    await registerOpenCodeMcpServer();
    void vscode.window.showInformationMessage(
      'Event Horizon: OpenCode plugin + MCP tools installed! Restart OpenCode to see your agent appear.',
    );
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    void vscode.window.showErrorMessage(`Event Horizon: Failed to install OpenCode plugin — ${msg}`);
  }
}
